# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillctl" do
  version "0.4.0"

  on_macos do
    sha256 "8b47324c913a65491a01318c50fdaa35e5d5762a973d99d899711867e4f39fba"
    url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_darwin_universal.zip"
  end

  on_linux do
    on_intel do
      sha256 "e0dfe821c44c4f4e89d9c7cac0e868469d220bfd503a2cd3a10a9d9a2e5bb2d3"
      url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f1d7fb5bf503d169f8f1dd132e88d41d5bb5d05b0419bf5ef2fd155e6ca9ed7"
      url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillctl"
  desc "Verify, restore and revoke the Agent Skills your organisation signed"
  homepage "https://github.com/random1st/skilltrust"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillctl"
  binary "skilltrust-mcp"

  # No zap stanza required

end
