# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillctl" do
  version "0.4.1"

  on_macos do
    sha256 "8af95bf9eb632097df643aa5ceaba67d10501b59b5629e3045ea706556ac63b0"
    url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_darwin_universal.zip"
  end

  on_linux do
    on_intel do
      sha256 "54afc457db44b6172d4e632aa6ceae3b09c66d4f026481a7b4514a0cb392f133"
      url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9cd2db775154e6ad23b2890afb19e0bce5982929d772699580f428efea0c5b18"
      url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillctl"
  desc "Verify, restore and revoke the Agent Skills your organisation signed"
  homepage "https://github.com/random1st/skilltrust"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillctl"
  binary "skilltrust-mcp"

  # No zap stanza required

end
