# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillctl" do
  version "0.3.0"

  on_macos do
    sha256 "e2295fd79d0f7be2a3bf4ca01095f372a571d7fad1333c77b0e241199266b966"
    url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_darwin_universal.zip"
  end

  on_linux do
    on_intel do
      sha256 "e34b3f6b48dbb86b55104c9d4e01935f60acbf5a77dcea5a93e7b19cc70d09ec"
      url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6418a2e9060a8953320d660804e839c6987bc638040fce5db3d8a3096ea3aaf2"
      url "https://github.com/random1st/skilltrust/releases/download/v#{version}/skillctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillctl"
  desc "Verify, restore and revoke the Agent Skills your organisation signed"
  homepage "https://github.com/random1st/skilltrust"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillctl"
  binary "skilltrust-mcp"

  # No zap stanza required

end
